#!/usr/bin/env python3
"""Report finale stato sistema automazione"""

from datetime import datetime

import requests

print("📊 REPORT FINALE SISTEMA DI AUTOMAZIONE")
print("")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("")
print(f"✅ STATO ATTUALE (18 Aprile 2026 ore {datetime.now().strftime('%H:%M')})")
print("")

# Dashboard status
resp = requests.get("https://pronostici-calcio-professional.onrender.com/api/monitoring/accuracy")
data = resp.json()

print(f"🎯 Dashboard: {data['status_message']}")
print(f"📈 Accuracy: {data['accuracy_lifetime_pct']:.1f}% su {data['predictions_lifetime']} partite")
print(f"💰 ROI lifetime: {data.get('roi_lifetime_pct', 0):.1f}%")
print("")

# Tracking CSV status
resp2 = requests.get("https://pronostici-calcio-professional.onrender.com/api/export_tracking_csv")
csv_data = resp2.json()

print(f"📁 Tracking CSV: {csv_data['total_predictions']} predizioni totali")
print(f"📅 Ultimo aggiornamento: {csv_data['last_update'][:19]}")
print("")

print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("")
print("🤖 WORKFLOW CONFIGURATI")
print("")
print("1️⃣ auto-update.yml")
print("   ⏰ Giornaliero 05:00 UTC (07:00 Italy)")
print("   🎯 Aggiorna dati da football-data.co.uk")
print("")
print("2️⃣ daily-predictions.yml")
print("   ⏰ Giornaliero 08:00 UTC (10:00 Italy)")
print("   🎯 Genera predizioni partite upcoming")
print("   📊 Prossimo run: Domani mattina")
print("")
print("3️⃣ update-results.yml")
print("   ⏰ Giornaliero 22:00 UTC (00:00 Italy)")
print("   🎯 Scarica risultati e aggiorna tracking")
print("   📊 Prossimo run: Oggi notte")
print("")
print("4️⃣ weekly-retrain.yml")
print("   ⏰ Settimanale Lunedì 02:00 UTC")
print("   🎯 Ritraining modelli ML con nuovi dati")
print("   📊 Prossimo run: Lunedì 21 Aprile")
print("")

print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("")
print("✨ FIX IMPLEMENTATI OGGI")
print("")
print("✅ CSV Corruption: Rimossa serializzazione pandas da Note field")
print("✅ Dashboard Count: Da 1 → 19 predizioni pending (corretto)")
print("✅ Auto-Update Results: Endpoint + workflow configurato")
print("✅ Monitoring: Status pending con icon ⏳")
print("")

print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("")
print("⏭️  PROSSIMI STEP AUTOMATICI")
print("")
print("🌙 OGGI 00:00 (22:00 UTC):")
print("   • update-results.yml scarica risultati partite 12-13 Aprile")
print("   • Aggiorna tracking CSV con esiti")
print("   • Commit su repo se ci sono update")
print("")
print("☀️ DOMANI 10:00 (08:00 UTC):")
print("   • daily-predictions.yml genera predizioni weekend")
print("   • Salva in tracking CSV")
print("   • Commit su repo")
print("")
print("📅 LUNEDÌ 21/04 02:00 UTC:")
print("   • weekly-retrain.yml ritraining modelli ML")
print("   • Commit nuovi modelli .pkl")
print("   • Auto-deploy Render")
print("")

print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("")
print("🎯 SISTEMA 100% AUTONOMO ✅")
print("")
print("Non serve intervento manuale - tutto automatizzato!")
print("Monitoraggio: Dashboard aggiornata real-time")
print("")
