"""Type stubs for monitoring module"""
from typing import Any, Callable, Dict, Optional, TypeVar
from collections.abc import Callable as CallableType

F = TypeVar('F', bound=Callable[..., Any])

class StructuredLogger:
    def info(self, message: str, **context: Any) -> None: ...
    def warning(self, message: str, **context: Any) -> None: ...
    def error(self, message: str, **context: Any) -> None: ...
    def get_stats(self) -> Dict[str, Any]: ...

class PerformanceMonitor:
    def record(self, endpoint: str, duration: float, error: bool = False) -> None: ...
    def get_stats(self) -> Dict[str, Any]: ...

class ErrorTracker:
    def record_error(self, error_type: str, message: str, context: Optional[Dict] = None) -> None: ...
    def get_error_summary(self) -> Dict[str, Any]: ...
    def get_recent_errors(self, limit: int = 100) -> list: ...

def get_logger() -> StructuredLogger: ...
def get_performance_monitor() -> PerformanceMonitor: ...
def get_error_tracker() -> ErrorTracker: ...
def monitor_performance(endpoint_name: Optional[str] = None) -> Callable[[F], F]: ...
def log_request(request_data: Dict[str, Any]) -> None: ...
def log_cache_hit(key: str, hit: bool) -> None: ...
def log_api_call(api_name: str, success: bool, duration: float) -> None: ...
